name: Bug report
description: Report a defect
title: "fix: "
labels: [bug]
body:
  - type: input
    id: env
    attributes: { label: Environment, placeholder: "macOS 14 / Python 3.10 / VS Code 1.xx" }
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
  - type: textarea
    id: expected
    attributes: { label: Expected vs actual }
